### ISSUE TITLE
Отдавать ошибки

### ISSUE THREAD

**Issue by QuietV** [deesiigneer/pyspapi#14]
Если по какой-то причине возникла ошибка, то необходимо ее выводить, а не отдавать пустой список или None.

**Comment by deesiigneer** [comment]
Если ответ не 200, 201 - будет выведен статус код и message от сервера
#
https://github.com/deesiigneer/pyspapi/blob/c086954c25669e91f5d9bb4120f246d52c473cc3/pyspapi/api/api.py#L48
