### ISSUE TITLE
не устанавливается пакет

### ISSUE THREAD

**Issue by Janar0** [deesiigneer/pyspapi#8]
при попытке установить пакет начиная с версии  2.0.0a0 выдает данную ошибку, при этом более старые версии устанавливаются исправно
ОС: ubuntu с оболочкой kde plasma (kubuntu)
 `$  pip install pyspapi
Defaulting to user installation because normal site-packages is not writeable
Collecting pyspapi
  Using cached pyspapi-2.1.0.tar.gz (6.2 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-v1v63mlg/pyspapi_cc1625e6b2584d1085d786fa24bb1ca1/setup.py", line 6, in <module>
          with open("requirements.txt") as f:
      FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.`

**Comment by deesiigneer** [comment]
Забыл добавить манифест файл, теперь всё работает как часики, спасибо)
